server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERHATE_DLL_AUTO:validate}
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    enabled: ${FLYWAY_ENABLED:true}